### ISSUE TITLE
get_color doesn't work with Python 3.10+

### ISSUE THREAD

**Issue by deantonccns** [arvydas/blinkstick-python#96]
File "/home/payfree/.local/lib/python3.10/site-packages/blinkstick/blinkstick.py", line 482, in get_color
    if isinstance(get_color_func, collections.Callable):
AttributeError: module 'collections' has no attribute 'Callable'

because collections.Callable has been [moved to collections.abc.Callable](https://docs.python.org/3/whatsnew/3.10.html#removed) in python 3.10+.

Is there any plan to support newer Python version?
Thanks.

**Comment by deantonccns** [comment]
It turns out there is a package for 3.10+, then the issue can be closed.
